// flow-typed signature: a5c14d7a2c8902564e32cf07c1d148bd
// flow-typed version: <<STUB>>/@marv/components_v^0.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@marv/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@marv/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@marv/components/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/eslint-config-react-app_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@marv/components/lib/App/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@marv/components/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/classnames_v2.x.x'>;
}
declare module '@marv/components/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/eslint-config-react-app_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/eslint-config-react-app_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@marv/components/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@marv/components/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@marv/components/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@marv/components/lib/App/index.js' {
  declare module.exports: $Exports<'@marv/components/lib/App/index'>;
}
